### PR TITLE
add mdnext-tailwind template

### PR DESCRIPTION
**Pull request by ekafyi**
Hey Dom,

Here's the PR for https://github.com/domitriusclark/mdnext/issues/46

Screen Shot 2020-10-06 at 01 44 39

I also added extra information on the readme--I updated the Deploy buttons to deploy from `https://github.com/domitriusclark/mdnext-tailwind`, which does not exist currently. 

Let's go!

### CODE REVIEW

**Review by domitriusclark — COMMENTED** [review]
Can't wait to take this for a spin! Looks like an amazing start for Tailwind & mdnext!!! Thank you

Would you mind adding some resources to help someone new use this template ie Tailwind docs / tutorials / repos etc to the README?

**Comment by ekafyi** [comment]
Good idea about the resources!

I've already added basic information about the files to check for customizing their Tailwind setup to the [readme](https://github.com/domitriusclark/mdnext/blob/f35dce02ea9719791314f3ec81280e3db559c416/templates/mdnext-tailwind/README.md#tailwind-setup), but going to add resources as you suggested.

**Comment by ekafyi** [comment]
What do you think of this?

## Tailwind

This template uses the utility-first CSS framework **Tailwind** for styling. Take a look at the following files to get started.

— **_tailwind.config.js_**

Blank Tailwind configuration with the `purge` option to remove unused CSS in production, thus keeping the resulting CSS file small, and `theme.extend.colors` to add a custom color palette.

— **_postcss.config.js_**

PostCSS configuration file. Other than Tailwind, it uses Next.js's [default PostCSS configuration](https://nextjs.org/docs/advanced-features/customizing-postcss-config).

— **_src/tailwind.css_**

CSS file containing the `@tailwind` directive. Additionally, it contains examples of Tailwind's `@apply` directive and custom styles. You can rename and move it as you wish, but make sure you adjust the import path in `pages/_app.js`.

— **_src/components/ContentBox.js_** and **_src/components/Navbar.js_**

Examples of TailwindCSS in action in component files.

### Tailwind Resources

- [Tailwind Documentation](https://tailwindcss.com/)
	- [Configuration](https://tailwindcss.com/docs/configuration)
	- [Customizing Colors](https://tailwindcss.com/docs/customizing-colors)
	- [Directives](https://tailwindcss.com/docs/functions-and-directives) (`@tailwind`, `@apply`, `@layer`, etc)
- [Official Tailwind component examples](https://tailwindcss.com/components) – UI components
- [Tailwind Components](https://tailwindcomponents.com/) – free UI components by the community
- [Tailwind cheat sheet](https://tailwindcomponents.com/cheatsheet/)
- [Awesome Tailwind CSS](https://github.com/aniftyco/awesome-tailwindcss) – more Tailwind resources

**Comment by domitriusclark** [comment]
That looks absolutely perfect. Thank you so much for adding that section

**Comment by domitriusclark** [comment]
Last thing I could think of is changing the `repo` in your package to point to `mdnext-tailwind.git`

Otherwise this is good to go and will be merged once your next commits hit. Appreciate you!!

**Comment by ekafyi** [comment]
Done and done @domitriusclark !

Anything I could/should do about the `yarn.lock` conflict? Fetch from upstream and recommit, or remove it altogether in this PR? 🤔

**Comment by domitriusclark** [comment]
The `yarn.lock` thing is definitely my fault from trying to figure out what was wrong with the failing actions. Should be able to fetch and recommit. If not, I'll dig in and resolve :) Thank you so much @ekafyi

**Comment by ekafyi** [comment]
All fixed, @domitriusclark .

**Pull request merged**
