### PR TITLE
Refactor/drop getinitialprops

### PR DESCRIPTION
**Pull request by ljosberinn**
hey  there 👋

before any change, this was the output of `next build` - notice `First Load JS shared by all`:

before

applied the following changes:

1st commit:
- use latest chakra
- drop withPersistedTheme
- drop useThemePersistence
- adapt _app.js logic
- drop yarn.lock as npm variant was more up to date
- fix warnings about named default exports
- fix warnings about duplicate key

2nd commit:
- extract provider into Chakra
- adapt routes

output now:

after

### CODE REVIEW

**Comment by ljosberinn** [comment]
on the journey I re-discovered a bug in chakra which you seemed to implement a workaround for: the theme cookie was set without a `path` attribute so I fixed that in chakra right away - until the next rc it will sadly remain buggy.

**Comment by domitriusclark** [comment]
Super happy to have you digging into the Chakra stuff. 

Was definitely worried about hack and slashing the repo you sent me for implementing the theme persistence. Appreciate you @ljosberinn

**Comment by ljosberinn** [comment]
haha no worries, on the contrary, happy to see my repo was helpful! please dont mind the mess with the PR here, should've just rebased. feel free to drop this PR and copy over whatever part you choose to implement :)

**Comment by domitriusclark** [comment]
It definitely was. Great project structure too, really enjoyed poking around in there. Thanks for the work, I'll get it in here ASAP

**Comment by domitriusclark** [comment]
Brought your changes over! Thanks again for the help

**Pull request closed without merging**
